server:
  # 应用服务 WEB 访问端口
  port: 8080
  # 设置session过期时间
  servlet:
    session:
      timeout: 1800

spring:
  # Mybatis 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    # mysql安装在虚拟机上，因此ip地址也是localhost
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  # json中的null属性不会显示
  jackson:
    default-property-inclusion: non_null
  # redis配置
  # 同理redis部署在虚拟机的docker上面，host也是本机ip地址
  redis:
    host: 127.0.0.1
    port: 6379
  # 配置rabbitMQ
  # rabbitMQ和redis的情况一致
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest

mybatis:
  # 自动将下划线命名法转换为驼峰命名法
  configuration:
    map-underscore-to-camel-case: true
    # 控制台输出sql语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 解决*Mapper.xml文件找不到的问题，classpath本质是编译后的target/classes目录
#  mapper-locations: classpath:mapper/*.xml

logging:
  pattern:
    # 修改日志的格式
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %magenta(%-5level) %green([%-50.50class]) >>> %cyan(%msg) %n"
  level:
    # 设置日志最低级别
    garry.community: debug
