server:
  port: 8081
  servlet:
    context-path: /member # 项目的前缀

spring:
  application:
    name: member
  datasource: # Mybatis 数据库连接配置
    driver-class-name: com.mysql.jdbc.Driver  # driver-class-name：5.7版本为 com.mysql.jdbc.Driver；8.0版本为 com.mysql.cj.jdbc.Driver
    username: garry_train_member
    password: garry_train_member
    url: jdbc:mysql://localhost:3306/train_member?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml  # 指定对应的 xml文件的位置为：target/classes/mapper下的所有文件夹的所有.xml文件

logging:
  level:
    garry:
      train:
        member:
          mapper: trace # garry.train.member.mapper下的日志等级设置为 trace，可以打印出 sql

aliyun:
  sms:  # 短信发送服务的配置参数
    accessKeyId: LTAI5t7NeYCn6aSXPeVcU4Sz
    accessKeySecret: dTOwgV9xKoXnjJwM4EFRMCrry1rGnd
    signName: Garry售票系统
    templateCode: SMS_472695133
