GET http://localhost:8080/business/admin/api-detail/query-all-list?pageNum=1&pageSize=10
Content-Type: application/json

###

GET http://localhost:8080/member/admin/api-detail/query-list?pageNum=1&pageSize=10
Content-Type: application/json

###
