# common模块由于被其它模块所依赖，因此 common/resources/config/application.yml的优先级最高！

spring:
  data:
    redis:  # Redis配置
      host: 127.0.0.1
      port: 6379
      database: 1
      timeout: 3000 # 读超时
      connectTimeout: 5000  # 连接超时
      lettuce:  # Lettuce连接池
        pool:
          min-idle: 5 # 最小空闲连接
          max-idle: 10  # 最大空闲连接
          max-active: 100 # 最大连接数
          max-wait: 2000  # 连接分配应该阻塞的最大时间
