server:
  port: 8082
  servlet:
    context-path: /business # 项目的前缀

spring:
  main:
    # 允许循环依赖，为了可以在删除 Train 时，删除 Train 下所有的 Station, Carriage, Seat
    # WARNING: 允许循环依赖可能会使应用的行为变得不可预测，因此应该将其作为最后的手段
    allow-circular-references: true
  datasource: # Mybatis 数据库连接配置
    driver-class-name: com.mysql.jdbc.Driver  # driver-class-name：5.7版本为 com.mysql.jdbc.Driver；8.0版本为 com.mysql.cj.jdbc.Driver
    username:
    password:
    url:

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml  # 指定对应的 xml文件的位置为：target/classes/mapper下的所有文件夹的所有.xml文件

logging:
  level:
    garry:
      train:
        business:
          mapper: info # garry.train.business.mapper下的日志等级设置为 trace，可以打印出 sql

websocket:
  message:
    server:
      uri: ws://localhost:9999/ws/message/ # 最后还要加一个 memberId

rocketmq:
  name-server: http://localhost:9876
  producer:
    group: default