POST http://localhost:8080/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "Garry",
  "idCard": "000000200401270000",
  "type": "3"
}

###

GET http://localhost:8080/member/passenger/query-list
Content-Type: application/json
token: {{token}}

{
  "memberId": null
}

###
