POST http://localhost:8080/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "占位",
  "idCard": "xxxxxxxxxxxxxxxxxx",
  "type": "1"
}

###

GET http://localhost:8080/member/passenger/query-list?pageNum=2&pageSize=12
Accept: application/json
token: {{token}}

###

POST http://localhost:8080/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1835310145152880640,
  "name": "Garry",
  "idCard": "123456789987654231",
  "type": "3"
}

###