server:
  port: 8083
  servlet:
    context-path: /batch # 项目的前缀

spring:
  datasource: # Mybatis 数据库连接配置
    driver-class-name: com.mysql.jdbc.Driver  # driver-class-name：5.7版本为 com.mysql.jdbc.Driver；8.0版本为 com.mysql.cj.jdbc.Driver
    username:
    password:
    url:

logging:
  level:
    garry:
      train:
        batch:
          mapper: trace # garry.train.business.mapper下的日志等级设置为 trace，可以打印出 sql
